language: python
os: linux
dist: bionic
if: branch = master or tag IS present
python: 3.6

before_script:
    # <travis hacks>
    - source /home/travis/virtualenv/python3*/bin/activate && pip install -r ./requirements.txt
    - alias python3=python
    - pip install -r ./requirements.txt
    # </travis hacks>
    - source /home/travis/virtualenv/python3*/bin/activate && pip install -r ./subpackages/rkd_python/requirements.txt

test_script: &test_script
    # RKD & RKD Core & Standardlib
    - source /home/travis/virtualenv/python3*/bin/activate && ./setup.py build
    - source /home/travis/virtualenv/python3*/bin/activate && ./setup.py sdist
    - source /home/travis/virtualenv/python3*/bin/activate && cd src && python3 -m unittest discover -s ../test

    # Subpackages: rkd_python
    - cd subpackages/rkd_python && make package tests

# show stdout/stderr immediately in tests (in RKD itself the buffering is turned off)
env:
    - PYTHONUNBUFFERED=true

jobs:
    allow_failures:
        env:
            - CAN_FAIL=true

    include:
        - stage: Test on Python 3.6
          python: 3.6
          script: *test_script


        - stage: Test on Python 3.7
          python: 3.7
          script: *test_script

        - stage: Test on Python 3.8
          python: 3.8
          script: *test_script

        - stage: Release
          python: 3.6
          script:
              - make release
              - cd subpackages/rkd_python && make release

        - stage: Test on Python 3.9 (allowed to fail)
          env: CAN_FAIL=true
          python: 3.9
          script: *test_script

        - stage: Test on Python NIGHTLY (allowed to fail)
          env: CAN_FAIL=true
          python: nightly
          script: *test_script
